# window dimensions duh; top, left, width, height
window_dimensions: [675, 6, 953, 437] # full screen
state_window_dimensions: [965, 65, 840, 130] # smallest screen w/ all buttons
gold_storage_dimensions: [690, 772, 1, 1]
elixir_storage_dimensions: [726, 772, 1, 1]

left: 6
right: 961
top: 675
bottom: 1112
width: 953
height: 437

# home base buttons
attack_button: [100, 1050] # home base -> attack
find_match_button: [170, 975] # home base -> attack -> find match
find_ranked_match_button: [356, 975] # home base -> attack -> find ranked match
builder_button: [463, 695] # builder icon -> upgrade menu
laboratory_button: [377, 695] # laboratory icon -> upgrade menu
profile_button: [88, 695] # home base -> profile
league_button: [87, 736] # home base -> current league
battle_log_button: [87, 775] # home base -> battle log
chat_button: [87, 866] # home base -> clan chat
war_button: [87, 955] # home base -> war
army_button: [87, 997] # home base -> view army
battle_pass_button: [163, 1070] # home base -> battle pass
events_button: [206, 1070] # home base -> events page
news_button: [805, 1070] # home base -> news page
shop_button: [862, 1054] # home base -> shop
settings_button: [880, 996] # home base -> settings
edit_base_button: [880, 956] # home base -> edit base layout

# battle buttons
end_battle_button: [107, 1005] # scouting/attacking state -> end battle
surrender_button: [107, 1005] # scouting/attacking state -> end battle
confirm_surrender_button: [555, 940] # attacking state -> end battle -> surrender
next_button: [850, 995] # scouting state -> next base
return_home_button: [480, 1045] # battle ended state -> return home
base_right_corner: [840, 877]
base_bottom_corner: [505, 1015]

# hotbar buttons
super_barbs_button: [227, 1063]
siege_machine_button: [280, 1063]
barbarian_king_button: [337, 1063]
archer_queen_button: [387, 1063]
grand_warden_button: [436, 1063]
royal_champion_button: [485, 1063]
earthquake_button: [540, 1063]
lightning_button: [590, 1063]

# error handling
reload_game_button: [480, 935] # inactivivity popup -> reload game
