normalized: true
points:
- - 0.3096976016684046
  - 0.11678004535147392
- - 0.8107403545359749
  - 0.6111111111111112
- - 0.13451511991657977
  - 0.6111111111111112
- - 0.23722627737226276
  - 0.2857142857142857
- - 0.16319082377476538
  - 0.5544217687074829
- - 0.18821689259645463
  - 0.6587301587301587
- - 0.3347236704900938
  - 0.01473922902494331
- - 0.11105318039624609
  - 0.5011337868480725
- - 0.2596454640250261
  - 0.22789115646258504
- - 0.13712200208550573
  - 0.3344671201814059
- - 0.28779979144942647
  - 0.060090702947845805
- - 0.7116788321167883
  - 0.0691609977324263
- - 0.9608967674661105
  - 0.4501133786848073
- - 0.20959332638164754
  - 0.6632653061224489
- - 0.2132429614181439
  - 0.7709750566893424
- - 0.6856100104275287
  - 0.011337868480725623
- - 0.7606882168925965
  - 0.1235827664399093
- - 0.13816475495307612
  - 0.6587301587301587
- - 0.18665276329509906
  - 0.2857142857142857
- - 0.08394160583941605
  - 0.4965986394557823
- - 0.2867570385818561
  - 0.17346938775510204
- - 0.8362877997914494
  - 0.2777777777777778
- - 0.7111574556830031
  - 0.17006802721088435
- - 0.8102189781021898
  - 0.7210884353741497
- - 0.1845672575599583
  - 0.6133786848072562
- - 0.8858185610010427
  - 0.5521541950113379
- - 0.23774765380604795
  - 0.1235827664399093
- - 0.7606882168925965
  - 0.7721088435374149
- - 0.7387904066736184
  - 0.17573696145124718
- - 0.8613138686131386
  - 0.6133786848072562
- - 0.08550573514077164
  - 0.391156462585034
- - 0.162148070907195
  - 0.3922902494331066
- - 0.36287799791449427
  - 0.01473922902494331
- - 0.18769551616266944
  - 0.22448979591836735
- - 0.23566214807090718
  - 0.6621315192743764
- - 0.10948905109489052
  - 0.6099773242630385
- - 0.6595411887382691
  - 0.0691609977324263
- - 0.16058394160583941
  - 0.6621315192743764
- - 0.8096976016684045
  - 0.2789115646258503
- - 0.7095933263816475
  - 0.7709750566893424
- - 0.8602711157455682
  - 0.3321995464852608
- - 0.7872784150156413
  - 0.2789115646258503
- - 0.9139728884254432
  - 0.4444444444444444
- - 0.7867570385818561
  - 0.17687074829931973
- - 0.16058394160583941
  - 0.3412698412698413
- - 0.8357664233576643
  - 0.3401360544217687
- - 0.23566214807090718
  - 0.23129251700680273
- - 0.2122002085505735
  - 0.7165532879818595
- - 0.7601668404588112
  - 0.22448979591836735
- - 0.11209593326381648
  - 0.5555555555555556
- - 0.13712200208550573
  - 0.5022675736961452
- - 0.8884254431699687
  - 0.3321995464852608
- - 0.7851929092805006
  - 0.2233560090702948
- - 0.08706986444212722
  - 0.5555555555555556
- - 0.3347236704900938
  - 0.11791383219954649
- - 0.21063607924921793
  - 0.6077097505668935
- - 0.13816475495307612
  - 0.3945578231292517
- - 0.6856100104275287
  - 0.12131519274376418
- - 0.8357664233576643
  - 0.608843537414966
- - 0.7382690302398331
  - 0.22675736961451248
- - 0.7851929092805006
  - 0.6666666666666666
- - 0.28832116788321166
  - 0.7687074829931972
- - 0.10896767466110532
  - 0.4501133786848073
- - 0.8847758081334723
  - 0.4965986394557823
- - 0.8362877997914494
  - 0.3888888888888889
- - 0.13712200208550573
  - 0.4489795918367347
- - 0.08759124087591241
  - 0.4444444444444444
- - 0.8128258602711157
  - 0.6587301587301587
- - 0.05995828988529719
  - 0.5022675736961452
- - 0.2591240875912409
  - 0.06689342403628118
- - 0.7116788321167883
  - 0.12244897959183673
- - 0.1611053180396246
  - 0.28458049886621317
- - 0.2132429614181439
  - 0.23129251700680273
- - 0.7356621480709072
  - 0.7709750566893424
- - 0.3112617309697602
  - 0.06349206349206349
- - 0.9098018769551617
  - 0.5045351473922902
- - 0.6845672575599583
  - 0.06575963718820861
- - 0.8597497393117831
  - 0.3866213151927438
- - 0.8133472367049009
  - 0.3412698412698413
- - 0.6386861313868614
  - 0.007936507936507936
- - 0.7596454640250261
  - 0.17800453514739228
- - 0.7601668404588112
  - 0.6609977324263039
- - 0.835245046923879
  - 0.22448979591836735
- - 0.13555787278415016
  - 0.28458049886621317
- - 0.3597497393117831
  - 0.06349206349206349
- - 0.20907194994786235
  - 0.2789115646258503
- - 0.8628779979144943
  - 0.6678004535147393
- - 0.23670490093847757
  - 0.7721088435374149
- - 0.8613138686131386
  - 0.5555555555555556
- - 0.8362877997914494
  - 0.6632653061224489
- - 0.26225234619395205
  - 0.11678004535147392
- - 0.1611053180396246
  - 0.6122448979591837
- - 0.8123044838373306
  - 0.22448979591836735
- - 0.2340980187695516
  - 0.7210884353741497
- - 0.8852971845672576
  - 0.6054421768707483
- - 0.28832116788321166
  - 0.11791383219954649
- - 0.31334723670490094
  - 0.01020408163265306
- - 0.16006256517205422
  - 0.2290249433106576
- - 0.2596454640250261
  - 0.7165532879818595
- - 0.18665276329509906
  - 0.336734693877551
- - 0.3102189781021898
  - 0.7755102040816326
- - 0.8639207507820647
  - 0.282312925170068
- - 0.7638164754953076
  - 0.7131519274376418
- - 0.13816475495307612
  - 0.5544217687074829
- - 0.8602711157455682
  - 0.4977324263038549
- - 0.8368091762252347
  - 0.5510204081632653
- - 0.735140771637122
  - 0.1235827664399093
- - 0.05995828988529719
  - 0.445578231292517
- - 0.7867570385818561
  - 0.7165532879818595
- - 0.9374348279457768
  - 0.4444444444444444
- - 0.11105318039624609
  - 0.3956916099773243
- - 0.26277372262773724
  - 0.17346938775510204
- - 0.20907194994786235
  - 0.17006802721088435
- - 0.737747653806048
  - 0.717687074829932
- - 0.38425443169968715
  - 0.005668934240362812
- - 0.6120959332638165
  - 0.007936507936507936
- - 0.11105318039624609
  - 0.3344671201814059
- - 0.8884254431699687
  - 0.4501133786848073
- - 0.3373305526590198
  - 0.0691609977324263
- - 0.8847758081334723
  - 0.3877551020408163
- - 0.1845672575599583
  - 0.7154195011337868
- - 0.26329509906152243
  - 0.7675736961451247
- - 0.9374348279457768
  - 0.5045351473922902
- - 0.6355578727841501
  - 0.06689342403628118
- - 0.9108446298227321
  - 0.5498866213151927
- - 0.7367049009384776
  - 0.06575963718820861
- - 0.7846715328467153
  - 0.7732426303854876
- - 0.06047966631908238
  - 0.3900226757369615
- - 0.9103232533889468
  - 0.3922902494331066
- - 0.6637122002085506
  - 0.012471655328798186
- - 0.235140771637122
  - 0.17233560090702948
